- name: Setup Security Agent on AWS EC2 Instance.
  hosts: takehomechallenge
  tasks:
    - name: Create directory
      become: true 
      file:
        path: /opt/csg_security_agent
        state: directory
    - name: Copy security agent script
      become: true 
      copy:
        src: ../resources/security_agent_installer_linux_amd64_v1.0.0.sh
        dest: /opt/csg_security_agent/security_agent_installer.sh
    - name: Copy security agent configuration
      become: true 
      copy:
        src: ../resources/security_agent_config.conf
        dest: /opt/csg_security_agent
    - name: Execute the security agent script
      become: true 
      shell: |
        cd /opt/csg_security_agent
        chmod 755 security_agent_installer.sh
        ./security_agent_installer.sh --config security_agent_config.conf --token {{ security_agent_token }}


